[package]
name = "tsbundler"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "C API for tree-sitter syntax highlighting with built-in grammars and themes"

[lib]
name = "irisutils"
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
highlight-spans = { version = "0.9.0", path = "../highlight-spans" }
theme-engine = { version = "0.9.0", path = "../theme-engine" }
render-ansi  = { version = "0.9.0", path = "../render-ansi" }
